Rails.application.routes.draw do
  get "auth/discord/callback" => "session#create"
  get "card/gallery/:set/:id" => "card#gallery"
  get "card/:set/:id" => "card#show"
  get "card/:set/:id/:name" => "card#show"
  get "card" => "card#index"
  get "set/:id/verify_scans" => "set#verify_scans"
  get "set/:id/missing_scans" => "set#missing_scans"
  get "set/:id" => "set#show"
  get "set" => "set#index"
  get "artist/:id" => "artist#show"
  get "artist" => "artist#index"
  get "event" => "event#index"
  get "event/cssl" => "event#cssl_index"
  get "format/:id" => "format#show"
  get "format" => "format#index"
  get "help/syntax" => "help#syntax"
  get "help/rules" => "help#rules"
  get "help/contact" => "help#contact"
  get "list" => "card#list"
  get "logout" => "session#destroy"
  get "deck/crawl/:id" => "deck#show_crawl"
  get "deck/ech/:id" => "deck#show_ech"
  get "deck/:set/:id" => "deck#show"
  get "deck/:set/:id/download" => "deck#download"
  get "deck/visualize" => "deck#visualize"
  post "deck/visualize" => "deck#visualize"
  get "deck" => "deck#index"
  get "sealed" => "sealed#index"
  get "exh" => "exh#index"
  get "exh/news" => "exh#news"
  get "exh/todo" => "exh#todo"
  get "exh/vote/:name" => "exh#vote"
  get "preferences" => "session#preferences"
  post "preferences" => "session#preferences"
  get "/" => "card#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
